### ISSUE TITLE
Add a dev_cmd(s) to bump the package versions

### ISSUE THREAD

**Issue by PatrickLehnerXI** [XITASO/devcmd#10]
So far, we've been versioning `devcmd` and `devcmd-cli` in lockstep because our early issues and changes always affected both packages.
In the future, `devcmd-cli` should ideally get less frequent releases than `devcmd`.

Bumping the package versions has some pitfalls, so we should add dev_cmd(s) to automate this process.

* When bumping `devcmd-cli`'s version, the dependency in `devcmd` must be updated accordingly.
* When bumping `devcmd`'s version, the dependencies in the example projects and in our own dev_cmds must be updated accordingly.
* In both cases, an appropriate git tag must be created (deciding a tag naming pattern for non-lockstep versioning is part of this ticket)

**Comment by lehnerpat** [comment]
I'm working on this.
